name: "Test Custom Action"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run custom action
        id: testingAction
        uses: diabotez/barum@v0.1.0
        with:
          name: Dalwar

      - name: Display output
        run: echo "Greeting ${{ steps.testingAction.outputs.greeting }}"