name: "Test Custom Action"

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: false
        default: Dalwar
        type: string
env:
  GREET: Dalwar
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract name
        run: echo "WHO_TO_GREET=${{ inputs.name || env.GREET }}" >> $GITHUB_ENV

      - name: Run custom action
        id: hello
        uses: diabotez/barum@v0.1.1
        with:
          who-to-greet: $WHO_TO_GREET

      - name: Display output
        run: echo "$WHO_TO_GREET 's greeting time was ${{ steps.hello.outputs.time }}"