name: "Test Custom Action"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run custom action
        id: hello
        uses: diabotez/barum@v0.1.1
        env:
          WHO_TO_GREET: Dalwar
        with:
          who-to-greet: $WHO_TO_GREET

      - name: Display output
        run: echo "${{steps.hello.env.WHO_TO_GREET}}'s greeting time was ${{ steps.hello.outputs.time }}"